[package]
name = "attos_pixoo64"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.44", features = ["rt-multi-thread", "rt", "macros"] }
